AWSTemplateFormatVersion: '2010-09-09'  
Metadata:   
  License: Apache-2.0  
Description: 'AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete:  
  Sample template showing how to create a publicly accessible S3 bucket configured  
  for website access with a deletion policy of retain on delete. **WARNING** This  
  template creates an S3 bucket that will NOT be deleted when the stack is deleted.  
  You will be billed for the AWS resources used if you create a stack from this template.'  
    
Parameters:   
  AdeelS3BucketName:  
    Type: String  
    Description: S3 Bucket Name 
    Defalut: adeel-infrastructure-scripts 
     
Resources:  
  S3Bucket:  
    Type: AWS::S3::Bucket  
    Properties:  
      BucketName: !Ref AdeelS3BucketName  
      WebsiteConfiguration:  
        IndexDocument: index.html  
        ErrorDocument: error.html  
    DeletionPolicy: Delete 
  MyInstance: 
    Type: AWS::EC2::Instance 
    Properties: 
      AvailabilityZone: us-east-1a 
      ImageId: ami-a4c7edb2 
      InstanceType: t2.micro 
 
   
Outputs:  
  WebsiteURL:  
    Value: !GetAtt [S3Bucket, WebsiteURL]  
    Description: URL for website hosted on S3  
  S3BucketSecureURL:  
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]  
    Description: Name of S3 bucket to hold website content  